services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: dolist-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./uploads/avatars:/app/uploads/avatars

    restart: unless-stopped