services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: dolist-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db

    restart: unless-stopped